version: "3.9"

services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    environment:
      - VITE_API_URL=http://localhost:3333

  server:
    build:
      context: ./server
    ports:
      - "3333:3333"
    volumes:
      - ./server:/app
      - /app/node_modules
      - sqlite-db:/app/prisma
    environment:
      - DATABASE_URL=file:./prisma/dev.db
    command: sh -c "npx prisma migrate deploy && node dist/index.js"

volumes:
  sqlite-db:
